import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Card, EmptyState, ErrorBox, FullPageSpinner, Modal } from "../components/ui";
import { api, errorMessage } from "../lib/api";
import type { CategoryRow, DepartmentRow } from "../lib/types";

export default function AdminCategoriesPage(){
 const [rows,setRows]=useState<CategoryRow[]>([]);const [departments,setDepartments]=useState<DepartmentRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [show,setShow]=useState(false);const [name,setName]=useState("");const [desc,setDesc]=useState("");const [sla,setSla]=useState(72);const [keywords,setKeywords]=useState("");const [dept,setDept]=useState("");const [saving,setSaving]=useState(false);const [formError,setFormError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [c,d]=await Promise.all([api<CategoryRow[]>("/api/categories"),api<DepartmentRow[]>("/api/departments")]);setRows(c);setDepartments(d);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setFormError("");try{await api("/api/categories",{method:"POST",body:{name,description:desc,sla_hours:sla,keywords:keywords.split(",").map(x=>x.trim()).filter(Boolean),default_department_id:dept?Number(dept):null}});setShow(false);setName("");setDesc("");setSla(72);setKeywords("");setDept("");await load();}catch(e){setFormError(errorMessage(e));}finally{setSaving(false);}}
 if(loading)return <FullPageSpinner/>;const open=rows.reduce((a,c)=>a+(c.open_complaints||0),0),breaches=rows.reduce((a,c)=>a+(c.sla_breaches||0),0);
 return <div className="adm-page"><header className="adm-page-head"><div><h1>Categories & SLA</h1><p>Operational categories, routing departments and real SLA performance.</p></div><button className="btn btn-primary btn-sm" onClick={()=>setShow(true)}>+ Create category</button></header>{error&&<ErrorBox message={error} onRetry={load}/>}
 <div className="adm-kpi-grid adm-kpi-grid-compact">{[["Categories",rows.length],["Open complaints",open],["Escalated",rows.reduce((a,c)=>a+(c.escalated_complaints||0),0)],["SLA Breaches",breaches]].map(([l,v])=><div className="adm-kpi adm-kpi-forest" key={String(l)}><span className="adm-kpi-label">{l}</span><span className="adm-kpi-value">{v}</span></div>)}</div>
 <Card>{rows.length?<div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Category</th><th>Department</th><th>SLA</th><th>Open</th><th>Escalated</th><th>SLA Breaches</th><th>Keywords</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong><div className="text-xs text-slate-500">{c.description||"Complaint category"}</div></td><td>{c.department_name||"General Support"}</td><td><span className="adm-badge info">{c.sla_hours}h</span></td><td>{c.open_complaints||0}</td><td>{c.escalated_complaints||0}</td><td><span className={c.sla_breaches?"adm-badge warn":"adm-badge ok"}>{c.sla_breaches||0}</span></td><td className="text-xs text-slate-500 max-w-[280px]">{(c.keywords||[]).slice(0,6).join(", ")||"Configured by rules"}</td></tr>)}</tbody></table></div>:<EmptyState title="No categories configured" hint="Create categories or run the rule seed to populate telecom support categories."/>}</Card>
 {show&&<Modal open title="Create category" onClose={()=>setShow(false)}><form className="space-y-3" onSubmit={submit}><div><label className="label">Name</label><input className="input mt-1" required value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Description</label><textarea className="input mt-1" rows={2} value={desc} onChange={e=>setDesc(e.target.value)}/></div><div><label className="label">Department</label><select className="input mt-1" value={dept} onChange={e=>setDept(e.target.value)}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div><label className="label">SLA hours</label><input className="input mt-1" type="number" min={1} value={sla} onChange={e=>setSla(Number(e.target.value))}/></div><div><label className="label">Keywords</label><input className="input mt-1" value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="sim, activation, blocked"/></div>{formError&&<p className="text-sm text-rose-600">{formError}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Creating…":"Create"}</button></div></form></Modal>}</div>;
}
