import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Card, EmptyState, ErrorBox, FullPageSpinner, Modal } from "../components/ui";
import { api, errorMessage } from "../lib/api";
import type { DepartmentRow } from "../lib/types";

export default function AdminDepartmentsPage() {
  const [rows, setRows] = useState<DepartmentRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(""); const [desc, setDesc] = useState(""); const [escalation, setEscalation] = useState(false); const [creating, setCreating] = useState(false); const [formError, setFormError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setRows(await api<DepartmentRow[]>("/api/departments")); } catch(e){setError(errorMessage(e));} finally{setLoading(false);} }, []);
  useEffect(()=>{void load();},[load]);
  async function handleCreate(e: FormEvent){e.preventDefault();setCreating(true);setFormError("");try{await api("/api/departments",{method:"POST",body:{name,description:desc,is_escalation_target:escalation}});setShowCreate(false);setName("");setDesc("");setEscalation(false);await load();}catch(e){setFormError(errorMessage(e));}finally{setCreating(false);}}
  if(loading)return <FullPageSpinner/>;
  return <div className="adm-page"><header className="adm-page-head"><div><h1>Departments</h1><p>Live workload, ownership and SLA pressure by support department.</p></div><button className="btn btn-primary btn-sm" onClick={()=>setShowCreate(true)}>+ Create department</button></header>{error&&<ErrorBox message={error} onRetry={load}/>}
    <div className="adm-kpi-grid adm-kpi-grid-compact">{[["Departments",rows.length],["Open",rows.reduce((a,d)=>a+(d.open_complaints||0),0)],["Unassigned",rows.reduce((a,d)=>a+(d.unassigned_complaints||0),0)],["SLA Risk",rows.reduce((a,d)=>a+(d.sla_risk||0),0)]].map(([l,v])=><div className="adm-kpi adm-kpi-forest" key={String(l)}><span className="adm-kpi-label">{l}</span><span className="adm-kpi-value">{v}</span></div>)}</div>
    <Card>{rows.length?<div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Department</th><th>Open</th><th>Assigned</th><th>Unassigned</th><th>Escalated</th><th>SLA Risk</th><th>Agents</th><th>Role</th></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><strong>{d.name}</strong><div className="text-xs text-slate-500">{d.description||"Support operations"}</div></td><td>{d.open_complaints||0}</td><td>{d.assigned_complaints||0}</td><td><span className={d.unassigned_complaints?"adm-badge warn":"adm-badge ok"}>{d.unassigned_complaints||0}</span></td><td>{d.escalated_complaints||0}</td><td><span className={d.sla_risk?"adm-badge warn":"adm-badge ok"}>{d.sla_risk||0}</span></td><td>{d.agent_count||0}</td><td>{d.is_escalation_target?<span className="adm-badge info">Escalation target</span>:<span className="adm-badge muted">Standard</span>}</td></tr>)}</tbody></table></div>:<EmptyState title="No departments configured" hint="Create the first support department to begin routing complaints."/>}</Card>
    {showCreate&&<Modal open title="Create department" onClose={()=>setShowCreate(false)}><form className="space-y-3" onSubmit={handleCreate}><div><label className="label">Name</label><input className="input mt-1" required value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Description</label><textarea className="input mt-1" rows={3} value={desc} onChange={e=>setDesc(e.target.value)}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={escalation} onChange={e=>setEscalation(e.target.checked)}/> Escalation target department</label>{formError&&<p className="text-sm text-rose-600">{formError}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="btn btn-primary" disabled={creating}>{creating?"Creating…":"Create"}</button></div></form></Modal>}</div>;
}
