import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Card, EmptyState, ErrorBox, FullPageSpinner, Pagination, StatusBadge, UrgencyBadge, Badge } from "../components/ui";
import { api, errorMessage } from "../lib/api";
import type { ComplaintBrief } from "../lib/types";

export default function AgentComplaintsPage(){
 const [params,setParams]=useSearchParams(); const filter=params.get("filter")||""; const [q,setQ]=useState(""); const [data,setData]=useState<{total:number;items:ComplaintBrief[]}|null>(null); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{setData(await api<{total:number;items:ComplaintBrief[]}>(`/api/agent/complaints`,{query:{q:q||undefined,filter:filter||undefined,page,page_size:20}}));setError("");}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[q,filter,page]);
 useEffect(()=>{void load();},[load]); useEffect(()=>{setPage(1)},[filter]);
 const title=useMemo(()=>filter==="pending"?"Pending complaints":filter==="urgent"?"Urgent queue":filter==="waiting"?"Waiting for customer":filter==="in_progress"?"In progress":filter==="escalated"?"Escalated":filter==="resolved"?"Resolved":"My complaints",[filter]);
 if(loading&&!data)return <FullPageSpinner/>;
 return <div className="adm-page agent-workspace"><div className="adm-page-head"><p className="agent-kicker">Customer support queue</p><h1>{title}</h1><p>These are complaints assigned to you. Open a case to read the full conversation and respond to the customer.</p></div>
   <Card><div className="agent-filterbar"><div className="agent-searchbox"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setPage(1);void load()}}} placeholder="Search complaint, customer or ID…"/></div><div className="agent-filterchips">{[["","All"],["pending","Pending"],["urgent","Urgent"],["in_progress","In progress"],["waiting","Waiting"],["escalated","Escalated"],["resolved","Resolved"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setParams(v?{filter:v}:{})}>{l}</button>)}</div></div>{error?<ErrorBox message={error} onRetry={()=>void load()}/>:data&&data.items.length?<><div className="agent-table-wrap"><table className="agent-table"><thead><tr><th>Customer</th><th>Complaint</th><th>Priority</th><th>Status</th><th>SLA</th><th></th></tr></thead><tbody>{data.items.map(c=><tr key={c.id}><td><div className="agent-customer"><span>{(c.customer_name||"C").slice(0,1).toUpperCase()}</span><div><strong>{c.customer_name||"Customer"}</strong><small>{c.customer_email||`Customer ID #${c.id}`}</small></div></div></td><td><Link to={`/agent/cases/${c.id}`} className="agent-table-title">{c.title}</Link><small>{c.code} · {c.issue_category||c.verified_category||"Support"}</small></td><td><UrgencyBadge urgency={c.verified_urgency||c.urgency}/><div className="mt-1"><Badge label={c.verified_priority||c.priority||"—"}/></div></td><td><StatusBadge status={c.status}/></td><td><span className={c.sla_due_at&&new Date(c.sla_due_at).getTime()<=Date.now()?"agent-sla danger":"agent-sla"}>{c.sla_due_at?new Date(c.sla_due_at).toLocaleString():"Pending"}</span></td><td><Link to={`/agent/cases/${c.id}`} className="btn btn-secondary btn-sm">Open</Link></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={20} total={data.total} onPage={setPage}/></>:<EmptyState title="No complaints in this queue" hint="New customer cases assigned to you will appear here automatically."/>}</Card>
 </div>;
}
