import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Badge, Card, ErrorBox, FullPageSpinner, StatusBadge, UrgencyBadge } from "../components/ui";
import { api, errorMessage } from "../lib/api";
import { formatDateTime, timeAgo } from "../lib/format";
import type { AgentCaseData, AgentMessage } from "../lib/types";

function Message({m}:{m:AgentMessage}){ const kind=m.sender_type; return <div className={`agent-message ${kind}`}><div className="agent-message-avatar">{kind==="customer"?"C":kind==="agent"?"A":"N"}</div><div className="agent-message-body"><div className="agent-message-head"><strong>{m.sender_name}</strong><span>{m.created_at?new Date(m.created_at).toLocaleString():""}</span></div><div className="agent-message-bubble">{m.text}</div>{kind==="agent"&&<small className="agent-message-note">Visible to customer</small>}</div></div> }

export default function AgentCasePage(){
 const {id}=useParams(); const nav=useNavigate(); const [data,setData]=useState<AgentCaseData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(""); const [actionMessage,setActionMessage]=useState(""); const [showActions,setShowActions]=useState(false); const [pendingAction,setPendingAction]=useState(""); const composer=useRef<HTMLTextAreaElement|null>(null);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api<AgentCaseData>(`/api/agent/complaints/${id}`));setError("");}catch(e){if(!silent)setError(errorMessage(e));}finally{if(!silent)setLoading(false);}},[id]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),10000);return()=>window.clearInterval(timer)},[load]);
 const send=async()=>{if(!message.trim()||busy)return;setBusy("reply");try{await api(`/api/agent/complaints/${id}/reply`,{method:"POST",body:{message:message.trim()}});setMessage("");await load();composer.current?.focus();}catch(e){setError(errorMessage(e));}finally{setBusy("")}};
 const openAction=(name:string)=>{setPendingAction(name);setShowActions(true);setActionMessage("");};
 const action=async(name:string)=>{if((name==="reject"||name==="request_info"||name==="resolve"||name==="escalate")&&!actionMessage.trim()){setError("Please write the customer-facing message/reason first.");return;}setBusy(name);try{await api(`/api/agent/complaints/${id}/action`,{method:"POST",body:{action:name,message:actionMessage.trim()}});setActionMessage("");setShowActions(false);setPendingAction("");await load();}catch(e){setError(errorMessage(e));}finally{setBusy("")}};
 const changeStatus=async(st:string)=>{if(!data||st===data.complaint.status)return;setBusy("set_status");try{await api(`/api/agent/complaints/${id}/action`,{method:"POST",body:{action:"set_status",status:st,message:""}});await load();}catch(e){setError(errorMessage(e));}finally{setBusy("")}};
 if(loading&&!data)return <FullPageSpinner/>;if(error&&!data)return <ErrorBox message={error} onRetry={()=>void load()}/>;if(!data)return null;const c=data.complaint;const ai=data.ai_summary;
 return <div className="adm-page agent-case-page">
  <div className="agent-case-top"><div><Link to="/agent/complaints" className="agent-back">← My complaints</Link><div className="agent-case-code">{c.code}</div><h1>{c.title}</h1><p>Customer complaint · updated {timeAgo(c.updated_at||c.created_at)}</p></div><div className="agent-case-badges"><UrgencyBadge urgency={c.verified_urgency||c.urgency}/><StatusBadge status={c.status}/><Badge label={c.verified_priority||c.priority||"Priority pending"}/></div></div>
  {error&&<ErrorBox message={error}/>}
  <div className="agent-case-grid">
   <section className="agent-conversation-card">
    <div className="agent-section-head"><div><span>LIVE COMPLAINT THREAD</span><h2>Customer conversation</h2><p>Chatbot and customer messages stay together here. Your replies are sent back to this same thread.</p></div><div className="agent-thread-live"><span/> Live</div></div>
    <div className="agent-conversation">{data.messages.length?data.messages.map(m=><Message key={m.id} m={m}/>):<div className="agent-empty"><div>💬</div><strong>No chat transcript linked</strong><span>Use the complaint details below to contact the customer.</span></div>}</div>
    <div className="agent-composer"><textarea ref={composer} value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Write a response to the customer…" rows={3}/><div><span>Enter to send · Shift+Enter for a new line</span><button className="btn btn-primary" disabled={!message.trim()||!!busy} onClick={()=>void send()}>{busy==="reply"?"Sending…":"Send to customer →"}</button></div></div>
   </section>
   <aside className="agent-case-side">
    <Card title="Customer"><div className="agent-profile"><div className="agent-profile-avatar">{(c.customer_name||"C").slice(0,1)}</div><div><strong>{c.customer_name||"Customer"}</strong><span>{c.customer_email||"No email"}</span><small>Customer ID #{c.customer_id ?? "—"}</small></div></div><div className="agent-facts"><div><span>Complaint ID</span><strong>{c.code}</strong></div><div><span>Channel</span><strong>{c.channel||"Support"}</strong></div><div><span>Created</span><strong>{formatDateTime(c.created_at)}</strong></div><div><span>SLA due</span><strong>{c.sla_due_at?formatDateTime(c.sla_due_at):"Not set"}</strong></div></div></Card>
    <Card title="AI handoff"><div className="agent-ai-summary"><div className="agent-ai-label">AI SUMMARY</div><p>{ai.summary||c.description}</p><div className="agent-ai-grid"><div><span>Category</span><strong>{ai.category||"—"}</strong></div><div><span>Urgency</span><strong>{ai.urgency||"—"}</strong></div><div><span>Priority</span><strong>{ai.priority||"—"}</strong></div><div><span>Sentiment</span><strong>{ai.sentiment||"—"}</strong></div></div>{ai.suggested_action&&<div className="agent-suggested"><span>Suggested next step</span><strong>{ai.suggested_action}</strong></div>}{ai.guidance&&<p className="agent-guidance">{ai.guidance}</p>}</div></Card>
    <Card title="Actions"><div className="agent-status-change" style={{display:"grid",gap:8,marginBottom:14}}><label style={{fontSize:12,fontWeight:700}}>Change status</label><div style={{display:"flex",gap:8}}><select id="agent-status-select" defaultValue={c.status} key={c.status} className="input" style={{flex:1,padding:"8px 10px",borderRadius:10,border:"1px solid rgba(0,0,0,.15)"}}>{[["PENDING","Pending"],["IN_PROGRESS","In progress"],["WAITING_CUSTOMER","Waiting for customer"],["ESCALATED","Escalated"],["RESOLVED","Resolved"],["REJECTED","Rejected"],["CLOSED","Closed"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="btn btn-primary" disabled={!!busy} onClick={()=>void changeStatus((document.getElementById("agent-status-select") as HTMLSelectElement).value)}>{busy==="set_status"?"Saving…":"Update"}</button></div><small style={{opacity:.7}}>Current: {c.status.replace(/_/g," ")}. The customer sees every status change in their thread.</small></div><div className="agent-action-stack"><button className="agent-action approve" disabled={!!busy} onClick={()=>void action("approve")}>✓ Approve / continue</button><button className="agent-action info" disabled={!!busy} onClick={()=>openAction("request_info")} >Ask for information</button><button className="agent-action resolve" disabled={!!busy} onClick={()=>openAction("resolve")} >Resolve complaint</button><button className="agent-action escalate" disabled={!!busy} onClick={()=>openAction("escalate")} >Escalate</button><button className="agent-action reject" disabled={!!busy} onClick={()=>openAction("reject")} >Reject request</button>{["RESOLVED","CLOSED","REJECTED"].includes(c.status)&&<button className="agent-action reopen" disabled={!!busy} onClick={()=>void action("reopen")}>Reopen complaint</button>}</div>{showActions&&<div className="agent-action-modal"><label>{c.status==="RESOLVED"?"Resolution note":"Customer-facing message / reason"}</label><textarea value={actionMessage} onChange={e=>setActionMessage(e.target.value)} rows={4} placeholder="Write the message the customer should see…"/><div className="agent-action-modal-buttons"><button className="btn btn-secondary" onClick={()=>setShowActions(false)}>Cancel</button><button className="btn btn-primary" onClick={()=>void action(pendingAction)}>Send</button></div><small>This message is saved in the same complaint thread and becomes visible to the customer.</small></div>}</Card>
   </aside>
  </div>
  <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card title="Complaint details"><p className="agent-detail-description">{c.description}</p><div className="agent-facts wide"><div><span>Category</span><strong>{c.verified_category||c.issue_category||"Pending AI analysis"}</strong></div><div><span>Department</span><strong>{c.verified_department||c.department||"Support"}</strong></div><div><span>Requested resolution</span><strong>{c.requested_resolution||"Not specified"}</strong></div><div><span>Previous complaints</span><strong>{c.previous_complaints}</strong></div></div></Card><Card title="Case timeline"><div className="agent-timeline">{data.history.map(h=><div key={h.id}><i/><div><strong>{h.to_status.replace(/_/g," ")}</strong><span>{h.note}</span><small>{h.created_at?new Date(h.created_at).toLocaleString():""}</small></div></div>)}</div></Card></div>
 </div>;
}
