import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, errorMessage } from "../lib/api";
import { FullPageSpinner, ErrorBox } from "../components/ui";

type Dash={profile:{full_name?:string;phone_number?:string;verification_status?:string};sims:Array<{id:number;phone_number:string;status:string;sim_type:string;current_package?:string;network:string}>;active_subscriptions:Array<{id:number;package?:{name:string;price:number};end_date?:string}>;recent_orders:Array<{order_code:string;order_type:string;product_label:string;order_status:string;amount:number}>;notifications:Array<{id:number;title:string;body:string}>;recent_complaints:Array<{code:string;title:string;status:string;priority:string}>;counts:{sims:number;active_sims:number;active_packages:number;open_complaints:number}};
export default function CustomerServicesPage(){
 const [data,setData]=useState<Dash|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true); const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await api<Dash>("/api/telecom/dashboard"));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[]); useEffect(()=>{void load();},[load]);
 if(loading)return <FullPageSpinner/>; if(error&&!data)return <ErrorBox message={error} onRetry={load}/>; if(!data)return null; const name=data.profile?.full_name?.split(" ")[0]||"Customer";
 return <div className="services-page"><header className="customer-page-heading services-heading"><div><p className="customer-kicker">Your PakSim hub</p><h1>Assalam-o-Alaikum, {name}</h1><p>Everything you need for your SIM, packages and support — without duplicate navigation or unnecessary screens.</p></div><button className="customer-button secondary" onClick={load}>↻ Refresh</button></header>
  <div className="services-stats"><div><span>Active SIMs</span><strong>{data.counts.active_sims}</strong><small>of {data.counts.sims} registered</small></div><div><span>Active packages</span><strong>{data.counts.active_packages}</strong><small>currently running</small></div><div><span>Open complaints</span><strong>{data.counts.open_complaints}</strong><small>need your attention</small></div><div><span>Account</span><strong>{data.profile.verification_status==="VERIFIED"?"Verified":"Active"}</strong><small>{data.profile.phone_number||"PakSim customer"}</small></div></div>
  <section className="services-section"><div className="customer-section-heading"><div><span>What do you need?</span><h2>PakSim services</h2></div><small>Choose a service to continue</small></div><div className="service-grid"><article><div className="service-icon-large">▣</div><h3>SIM services</h3><p>Buy a new SIM, manage your number, report a lost SIM or request a replacement.</p><Link to="/sims" className="service-action">Open My SIMs →</Link></article><article><div className="service-icon-large">◈</div><h3>Packages & offers</h3><p>Compare available plans, choose a SIM, review the price and complete payment.</p><Link to="/packages" className="service-action">Browse packages →</Link></article><article><div className="service-icon-large">⌁</div><h3>Internet & network</h3><p>Get guided help for signal, 4G/5G, calls, SMS and mobile data problems.</p><Link to="/" className="service-action">Ask Nova →</Link></article><article><div className="service-icon-large">✓</div><h3>Complaints & support</h3><p>Submit a complaint and follow its status from review through resolution.</p><Link to="/complaints" className="service-action">My complaints →</Link></article><article><div className="service-icon-large">↻</div><h3>Activity</h3><p>See SIM purchases, package activations, replacements and payment references.</p><Link to="/orders" className="service-action">View activity →</Link></article><article><div className="service-icon-large">✦</div><h3>Nova AI support</h3><p>Ask questions in English, Urdu or Roman Urdu and escalate when human help is needed.</p><Link to="/" className="service-action">Chat with Nova →</Link></article></div></section>
  <div className="services-lower-grid"><section className="services-panel"><div className="panel-head"><div><span>Your connections</span><h2>Registered SIMs</h2></div><Link to="/sims">View all →</Link></div>{data.sims.slice(0,4).map(s=><div className="mini-row" key={s.id}><div><strong>{s.phone_number}</strong><small>{s.sim_type} · {s.network} · {s.current_package||"No package"}</small></div><span className={`sim-status ${s.status.toLowerCase()}`}>{s.status}</span></div>)}{!data.sims.length&&<p className="muted">No SIMs yet.</p>}</section>
  <section className="services-panel"><div className="panel-head"><div><span>Support</span><h2>Latest complaints</h2></div><Link to="/complaints">View all →</Link></div>{data.recent_complaints.slice(0,4).map(c=><Link className="mini-row complaint-mini-row" to="/complaints" key={c.code}><div><strong>{c.title}</strong><small>{c.code} · {c.priority||"Standard"}</small></div><span>{c.status.replace(/_/g," ")}</span></Link>)}{!data.recent_complaints.length&&<p className="muted">No complaints yet. Nova can help you start one.</p>}</section></div>
 </div>;
}
