import { useCallback, useEffect, useMemo, useState } from "react";
import { api, errorMessage } from "../lib/api";
import { FullPageSpinner, ErrorBox } from "../components/ui";

type Pkg={id:number;code:string;name:string;description:string;category:string;price:number;validity_days:number;internet_data_mb:number;call_minutes:number;sms_count:number};
type Sim={id:number;phone_number:string;status:string};
const filters=["All","Special Plans","Group Plans","Annual Plans","Semi-Annual Plans","Monthly Plans","Weekly Plans"];
function bucket(p:Pkg){const n=(p.name+" "+p.category).toLowerCase();if(n.includes("group")||n.includes("3in1")||n.includes("5in1"))return "Group Plans";if(n.includes("annual")&& !n.includes("semi"))return "Annual Plans";if(n.includes("semi"))return "Semi-Annual Plans";if(n.includes("weekly"))return "Weekly Plans";if(n.includes("special"))return "Special Plans";return "Monthly Plans";}
function dataLabel(mb:number){return mb>=1024?`${(mb/1024).toFixed(mb%1024===0?0:1)} GB`:`${mb} MB`;}

export default function PackagesPage(){
 const [items,setItems]=useState<Pkg[]>([]),[sims,setSims]=useState<Sim[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Pkg|null>(null),[filter,setFilter]=useState("All"),[step,setStep]=useState(1),[simId,setSimId]=useState(""),[payment,setPayment]=useState("Wallet/Balance"),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [p,s]=await Promise.all([api<{items:Pkg[]}>("/api/telecom/packages"),api<{items:Sim[]}>("/api/telecom/sims")]);setItems(p.items||[]);setSims((s.items||[]).filter(x=>x.status==="ACTIVE"));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[]); useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>filter==="All"?items:items.filter(p=>bucket(p)===filter),[items,filter]);
 async function confirm(){if(!selected)return;setBusy(true);setError("");try{const r=await api<{order:{order_code:string}}>(`/api/telecom/packages/${selected.id}/subscribe`,{method:"POST",body:{sim_id:simId?Number(simId):undefined,payment_method:payment,payment_reference:`DEMO-${Date.now()}`}});setMsg(`${selected.name} activate ho gaya. Reference: ${r.order.order_code}`);setSelected(null);setStep(1);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 function open(p:Pkg){setSelected(p);setStep(1);setSimId(sims[0]?.id?String(sims[0].id):"");setPayment("Wallet/Balance");}
 if(loading)return <FullPageSpinner/>;
 return <div className="packages-page">
  <header className="customer-page-heading package-heading"><div><p className="customer-kicker">PakSim offers</p><h1>Packages</h1><p>Choose your plan, select the SIM, review the offer and pay — everything in one clear flow.</p></div></header>
  {error&&<ErrorBox message={error}/>} {msg&&<div className="package-success">✓ {msg}</div>}
  <div className="package-filters" role="tablist" aria-label="Package categories">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div>
  <div className="package-grid">{visible.map((p,i)=><article className={`package-card package-tone-${i%6}`} key={p.id}>
    <div className="package-banner"><div><span>{bucket(p).replace(" Plans","")}</span><strong>{p.name}</strong></div><b>{p.category}</b></div>
    <div className="package-body"><div className="package-price-row"><div><strong>Rs. {p.price.toLocaleString()}</strong><small>/{p.validity_days} day{p.validity_days===1?"":"s"}</small></div><span className="package-validity">{p.validity_days} days</span></div>
      <p className="package-description">{p.description}</p><div className="package-benefits"><span>◉ {dataLabel(p.internet_data_mb)} data</span><span>◉ {p.call_minutes.toLocaleString()} call minutes</span><span>◉ {p.sms_count.toLocaleString()} SMS</span></div>
      <div className="package-offer">✦ {p.category} offer · View details before purchase</div><button className="package-buy" onClick={()=>open(p)}>Review & pay <span>→</span></button>
    </div></article>)}</div>
  {visible.length===0&&<div className="customer-empty"><div className="empty-icon">◌</div><h2>No plans in this category</h2><p>Try another category to see the available PakSim offers.</p></div>}
  {selected&&<div className="customer-modal-backdrop"><div className="customer-modal package-modal"><div className="customer-modal-head"><div><span className="customer-kicker">Package purchase</span><strong>{selected.name}</strong><small>Simple checkout — no hidden steps</small></div><button onClick={()=>setSelected(null)}>×</button></div>
    <div className="purchase-steps"><span className={step>=1?"active":""}>1 <b>SIM</b></span><i/><span className={step>=2?"active":""}>2 <b>Payment</b></span><i/><span className={step>=3?"active":""}>3 <b>Confirm</b></span></div>
    {step===1&&<div className="purchase-step"><div className="purchase-summary"><strong>{selected.name}</strong><span>Rs. {selected.price.toLocaleString()} · {selected.validity_days} days · {dataLabel(selected.internet_data_mb)}</span></div><label className="label">Which SIM should receive this package?<select className="input mt-1" value={simId} onChange={e=>setSimId(e.target.value)}><option value="">Select an active SIM</option>{sims.map(s=><option key={s.id} value={s.id}>{s.phone_number}</option>)}</select></label><div className="purchase-note">Your package is activated on the selected number after the payment/confirmation step.</div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="customer-button primary" disabled={!simId} onClick={()=>setStep(2)}>Continue →</button></div></div>}
    {step===2&&<div className="purchase-step"><div className="purchase-summary"><strong>Payment</strong><span>Amount due: Rs. {selected.price.toLocaleString()}</span></div><div className="payment-options">{["JazzCash","Easypaisa","Debit/Credit Card (Demo)","Wallet/Balance"].map(x=><button key={x} className={payment===x?"selected":""} onClick={()=>setPayment(x)}><span>{x.includes("Demo")?"▣":"◈"}</span><b>{x}</b><small>{x.includes("Demo")?"Demo gateway":"Available payment option"}</small></button>)}</div><p className="demo-note">Demo payment only: this project records the payment/reference in the database; no real money is charged.</p><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setStep(1)}>← Back</button><button className="customer-button primary" onClick={()=>setStep(3)}>Review purchase →</button></div></div>}
    {step===3&&<div className="purchase-step"><div className="final-review"><div><span>Package</span><strong>{selected.name}</strong></div><div><span>SIM</span><strong>{sims.find(s=>String(s.id)===simId)?.phone_number}</strong></div><div><span>Payment</span><strong>{payment}</strong></div><div><span>Total</span><strong>Rs. {selected.price.toLocaleString()}</strong></div></div><div className="purchase-note success-note">After confirmation, an activity/reference record is created and the package is activated for the selected SIM.</div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setStep(2)}>← Back</button><button className="customer-button primary" disabled={busy} onClick={()=>void confirm()}>{busy?"Processing…":"Confirm & activate"}</button></div></div>}
  </div></div>}
 </div>;
}
