import { useCallback, useEffect, useState } from "react";
import { api, errorMessage } from "../lib/api";
import { FullPageSpinner, ErrorBox } from "../components/ui";

type Sim={id:number;phone_number:string;sim_number_masked:string;sim_type:string;network:string;status:string;current_package?:string;activation_date?:string};
const emptyBuy={full_name:"",cnic:"",date_of_birth:"",contact_number:"",sim_type:"Prepaid",network:"4G",delivery_address:"",city:"",postal_area:"",offer_code:"",payment_method:""};
const statusLabel=(s:string)=>({ACTIVE:"Active",LOST:"Blocked — lost",BLOCKED:"Blocked",REPLACEMENT_REQUESTED:"Replacement requested",PENDING:"Pending"}[s]||s);

export default function SimsPage(){
 const [items,setItems]=useState<Sim[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[showBuy,setShowBuy]=useState(false),[buyStep,setBuyStep]=useState(1),[showLost,setShowLost]=useState<number|null>(null),[showReplace,setShowReplace]=useState<number|null>(null),[buy,setBuy]=useState(emptyBuy),[lost,setLost]=useState({reason:"Lost",description:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const d=await api<{items:Sim[]}>("/api/telecom/sims");setItems(d.items||[]);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[]); useEffect(()=>{void load();},[load]);
 async function buySim(){setBusy(true);setError("");try{const r=await api<{order:{order_code:string};payment_required:boolean}>("/api/telecom/sims/purchase",{method:"POST",body:buy});setMsg(`${r.order.order_code} created. ${r.payment_required?"Payment is required before activation.":"Your valid offer makes the SIM free."}`);setShowBuy(false);setBuyStep(1);setBuy(emptyBuy);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function reportLost(e:React.FormEvent){e.preventDefault();if(showLost==null)return;setBusy(true);try{const r=await api<{request_code:string}>(`/api/telecom/sims/${showLost}/lost`,{method:"POST",body:{...lost,confirm:true}});setMsg(`Request ${r.request_code} created. The SIM is blocked. You can request a replacement with the same number.`);setShowLost(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function replaceSim(id:number){setBusy(true);try{const r=await api<{order:{order_code:string}}>(`/api/telecom/sims/${id}/replacement`,{method:"POST"});setMsg(`Replacement ${r.order.order_code} created. Same phone number, new SIM/ICCID.`);setShowReplace(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(loading)return <FullPageSpinner/>;
 return <div className="sims-page">
  <header className="customer-page-heading sims-heading"><div><p className="customer-kicker">Your connections</p><h1>My SIMs</h1><p>Manage your numbers, check status and request a replacement without losing your existing number.</p></div><button className="customer-button primary" onClick={()=>{setShowBuy(true);setBuyStep(1);}}>＋ Buy new SIM</button></header>
  {error&&<ErrorBox message={error}/>} {msg&&<div className="package-success">✓ {msg}</div>}
  <div className="sims-summary"><div><span>Total SIMs</span><strong>{items.length}</strong></div><div><span>Active</span><strong>{items.filter(x=>x.status==="ACTIVE").length}</strong></div><div><span>Need attention</span><strong>{items.filter(x=>x.status!=="ACTIVE").length}</strong></div></div>
  <div className="sim-grid">{items.map(s=><article className={`sim-card ${s.status!=="ACTIVE"?"is-attention":""}`} key={s.id}><div className="sim-card-top"><div><span className="sim-label">PakSim mobile number</span><strong>{s.phone_number}</strong></div><span className={`sim-status ${s.status.toLowerCase()}`}>{statusLabel(s.status)}</span></div><div className="sim-details"><div><span>SIM / ICCID</span><strong>{s.sim_number_masked}</strong></div><div><span>Type</span><strong>{s.sim_type} · {s.network}</strong></div><div><span>Current package</span><strong>{s.current_package||"No active package"}</strong></div><div><span>Activation</span><strong>{s.activation_date?.slice(0,10)||"Pending"}</strong></div></div><div className="sim-card-actions">{s.status==="ACTIVE"&&<button className="customer-button secondary" onClick={()=>{setShowLost(s.id);setLost({reason:"Lost",description:""});}}>Report lost / stolen / damaged</button>}{["LOST","BLOCKED","REPLACEMENT_REQUESTED"].includes(s.status)&&<button className="customer-button primary" onClick={()=>setShowReplace(s.id)}>Replace SIM — keep same number</button>}</div></article>)}</div>
  {items.length===0&&<div className="customer-empty"><div className="empty-icon">▣</div><h2>No SIMs yet</h2><p>Start a new SIM order. Registration and delivery details are collected before the request is created.</p><button className="customer-button primary" onClick={()=>setShowBuy(true)}>Buy new SIM</button></div>}
  {showBuy&&<div className="customer-modal-backdrop"><div className="customer-modal sim-modal"><div className="customer-modal-head"><div><span className="customer-kicker">New SIM registration</span><strong>Buy New SIM</strong><small>Your SIM is not created until you finish this flow.</small></div><button onClick={()=>setShowBuy(false)}>×</button></div><div className="purchase-steps"><span className={buyStep>=1?"active":""}>1 <b>Details</b></span><i/><span className={buyStep>=2?"active":""}>2 <b>Delivery</b></span><i/><span className={buyStep>=3?"active":""}>3 <b>Review</b></span></div>
   {buyStep===1&&<div className="purchase-step"><div className="form-grid"><label className="label">Full name<input className="input mt-1" required value={buy.full_name} onChange={e=>setBuy({...buy,full_name:e.target.value})}/></label><label className="label">CNIC<input className="input mt-1" required placeholder="35202-1234567-1" value={buy.cnic} onChange={e=>setBuy({...buy,cnic:e.target.value})}/></label><label className="label">Date of birth<input type="date" className="input mt-1" value={buy.date_of_birth} onChange={e=>setBuy({...buy,date_of_birth:e.target.value})}/></label><label className="label">Contact number<input className="input mt-1" required value={buy.contact_number} onChange={e=>setBuy({...buy,contact_number:e.target.value})}/></label><label className="label">SIM type<select className="input mt-1" value={buy.sim_type} onChange={e=>setBuy({...buy,sim_type:e.target.value})}><option>Prepaid</option><option>Postpaid</option></select></label><label className="label">Network<select className="input mt-1" value={buy.network} onChange={e=>setBuy({...buy,network:e.target.value})}><option>4G</option><option>5G</option></select></label></div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setShowBuy(false)}>Cancel</button><button className="customer-button primary" disabled={!buy.full_name||!buy.cnic||!buy.contact_number} onClick={()=>setBuyStep(2)}>Continue →</button></div></div>}
   {buyStep===2&&<div className="purchase-step"><label className="label">Delivery address<textarea className="input mt-1" required rows={3} value={buy.delivery_address} onChange={e=>setBuy({...buy,delivery_address:e.target.value})} placeholder="House / street / landmark"/></label><div className="form-grid"><label className="label">City<input className="input mt-1" required value={buy.city} onChange={e=>setBuy({...buy,city:e.target.value})}/></label><label className="label">Area / postal info<input className="input mt-1" value={buy.postal_area} onChange={e=>setBuy({...buy,postal_area:e.target.value})}/></label><label className="label">Offer code<input className="input mt-1" placeholder="If you have an offer" value={buy.offer_code} onChange={e=>setBuy({...buy,offer_code:e.target.value})}/></label><label className="label">Payment method if paid<select className="input mt-1" value={buy.payment_method} onChange={e=>setBuy({...buy,payment_method:e.target.value})}><option value="">Select later if required</option><option>JazzCash</option><option>Easypaisa</option><option>Debit/Credit Card (Demo)</option><option>Wallet/Balance</option></select></label></div><div className="purchase-note">A FREE offer makes the SIM price Rs. 0. Otherwise the final price/payment requirement is shown in the order.</div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setBuyStep(1)}>← Back</button><button className="customer-button primary" disabled={!buy.delivery_address||!buy.city} onClick={()=>setBuyStep(3)}>Review →</button></div></div>}
   {buyStep===3&&<div className="purchase-step"><div className="final-review"><div><span>Name</span><strong>{buy.full_name}</strong></div><div><span>CNIC</span><strong>{buy.cnic}</strong></div><div><span>SIM</span><strong>{buy.sim_type} · {buy.network}</strong></div><div><span>Delivery</span><strong>{buy.city} · {buy.delivery_address}</strong></div><div><span>Offer</span><strong>{buy.offer_code||"No offer"}</strong></div><div><span>Payment</span><strong>{buy.payment_method||"Not required / selected later"}</strong></div></div><div className="purchase-note">We create the request only after you confirm. Delivery status and activation can then be tracked from your account activity.</div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setBuyStep(2)}>← Back</button><button className="customer-button primary" disabled={busy} onClick={()=>void buySim()}>{busy?"Creating…":"Confirm SIM request"}</button></div></div>}
  </div></div>}
  {showLost!=null&&<div className="customer-modal-backdrop"><div className="customer-modal"><div className="customer-modal-head"><div><span className="customer-kicker">SIM safety</span><strong>Why are you blocking this SIM?</strong><small>We need the reason before the SIM is blocked.</small></div><button onClick={()=>setShowLost(null)}>×</button></div><form onSubmit={reportLost} className="purchase-step"><label className="label">Reason<select className="input mt-1" value={lost.reason} onChange={e=>setLost({...lost,reason:e.target.value})}><option>Lost</option><option>Stolen</option><option>Damaged</option><option>Other</option></select></label><label className="label">Short description<textarea className="input mt-1" rows={3} value={lost.description} onChange={e=>setLost({...lost,description:e.target.value})} placeholder="Tell us what happened (optional for lost/stolen)."/></label><div className="purchase-note warning-note"><strong>Before you confirm</strong><br/>The SIM will be blocked after confirmation. Your phone number is not deleted; a replacement can be issued with the same number and a new ICCID.</div><div className="purchase-actions"><button type="button" className="customer-button secondary" onClick={()=>setShowLost(null)}>Cancel</button><button className="customer-button primary" disabled={busy}>{busy?"Blocking…":"Confirm & block SIM"}</button></div></form></div></div>}
  {showReplace!=null&&<div className="customer-modal-backdrop"><div className="customer-modal"><div className="customer-modal-head"><div><span className="customer-kicker">SIM replacement</span><strong>Keep your existing number</strong><small>Only the physical SIM/ICCID changes.</small></div><button onClick={()=>setShowReplace(null)}>×</button></div><div className="purchase-step"><div className="replacement-callout"><span>✓</span><div><strong>Same phone number</strong><p>A new SIM will be issued against your existing number. Your old SIM record stays in history.</p></div></div><div className="purchase-actions"><button className="customer-button secondary" onClick={()=>setShowReplace(null)}>Cancel</button><button className="customer-button primary" disabled={busy} onClick={()=>void replaceSim(showReplace)}>{busy?"Processing…":"Confirm replacement"}</button></div></div></div></div>}
 </div>;
}
